
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


version: 2
updates:
  # 1️⃣ **NPM Packages**
  - package-ecosystem: "npm"
    directory: "/" 
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5

  # 2️⃣ **GitHub Actions**
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"

  # 3️⃣ **Docker**
  - package-ecosystem: "docker"
    directory: "/" 
    schedule:
      interval: "weekly"
